### ISSUE TITLE
Error: vagrant ssh requires a specific VM name to target in a multi-VM environment.

### ISSUE THREAD

**Issue by akortesmaa** [solita/solita-cd#3]
In [Read the Docs](http://solita-cd.readthedocs.org/en/latest/) / [Setting up the Virtual Machine](http://solita-cd.readthedocs.io/en/latest/jenkins_ansible_vm.html) `vagrant ssh` fails with error: "This command requires a specific VM name to target in a multi-VM environment.". Should be `vagrant ssh ansible` instead?

Vagrant 1.8.5

**Comment by noidi** [comment]
Thanks for the report. I've made `ansible` the primary VM which should fix this issue.
